### ISSUE TITLE
Segmentation Fault and Failed to open data file exceptions

### ISSUE THREAD

**Issue by yasersharaf** [jfowkes/pycutest#14]
Amazing work @jfowkes.
I would like to use the package in Ubuntu 20.04, with GCC 9.3 and gfortran 9.3 with default python 3.8.
Upon running the 
```bash
python3 setup.py test
```
I get:
```bash
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing pycutest.egg-info/PKG-INFO
writing dependency_links to pycutest.egg-info/dependency_links.txt
writing requirements to pycutest.egg-info/requires.txt
writing top-level names to pycutest.egg-info/top_level.txt
reading manifest file 'pycutest.egg-info/SOURCES.txt'
writing manifest file 'pycutest.egg-info/SOURCES.txt'
running build_ext
runTest (pycutest.tests.test_basic_functionality.TestALLINITC_with_fixed) ... ERROR
runTest (pycutest.tests.test_basic_functionality.TestALLINITC_with_free) ... ERROR
runTest (pycutest.tests.test_basic_functionality.TestALLINITU) ... ERROR
runTest (pycutest.tests.test_basic_functionality.TestParamError) ... ok
runTest (pycutest.tests.test_basic_functionality.TestRemoval) ... ok
runTest (pycutest.tests.test_sifdecode_extras.TestAvailableParamsARGLALE) ... ok
runTest (pycutest.tests.test_sifdecode_extras.TestAvailableParamsBRATU) ... ok
runTest (pycutest.tests.test_sifdecode_extras.TestAvailableParamsROSENBR) ... ok
runTest (pycutest.tests.test_sifdecode_extras.TestClassification) ... ok
runTest (pycutest.tests.test_sifdecode_extras.TestFindProblems) ... ok
runTest (pycutest.tests.test_sifparam_chars.TestSROSENBR) ... ERROR
runTest (pycutest.tests.test_sparse_functionality.TestSparseConstrained) ... ERROR
runTest (pycutest.tests.test_sparse_functionality.TestSparseUnconstrained) ... ERROR

======================================================================
ERROR: runTest (pycutest.tests.test_basic_functionality.TestALLINITC_with_fixed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yaser/pycutest/pycutest/tests/test_basic_functionality.py", line 174, in runTest
    p = pycutest.import_problem('ALLINITC', drop_fixed_variables=False)
  File "/home/yaser/pycutest/pycutest/build_interface.py", line 349, in import_problem
    return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
  File "/home/yaser/pycutest/pycutest_cache/pycutest_cache_holder/ALLINITC/__init__.py", line 63, in <module>
    (n, m)=_pycutestitf._dims()
Exception: Failed to open data file

```
For installation, I used the following 
```bash
cd $HOME
git clone https://github.com/jfowkes/pycutest.git
export TRAVIS_BUILD_DIR=$HOME/pycutest ##example:$HOME/pycutest
cd $TRAVIS_BUILD_DIR
mkdir cutest

git clone https://github.com/ralna/ARCHDefs ./cutest/archdefs &&
git clone https://github.com/ralna/SIFDecode ./cutest/sifdecode &&
git clone https://github.com/ralna/CUTEst ./cutest/cutest &&
git clone https://bitbucket.org/optrove/sif ./cutest/mastsif

export ARCHDEFS="$HOME/pycutest/cutest/archdefs/"
export SIFDECODE="$HOME/pycutest/cutest/sifdecode"
export CUTEST="$HOME/pycutest/cutest/cutest"
export MASTSIF="$HOME/pycutest/cutest/mastsif/"
export MYARCH="pc64.lnx.gfo"

${ARCHDEFS}/install_optrove

#Manual says choose (5) GNU gfortran compiler but I chose (6)
#        (5) GNU gfortran 7 compiler
#        (6) GNU gfortran compiler



export PATH="${SIFDECODE}/bin:${PATH}"
export PATH="${CUTEST}/bin:${PATH}"
export MANPATH="${SIFDECODE}/man:${MANPATH}"
export MANPATH="${CUTEST}/man:${MANPATH}"
export MYARCH="pc64.lnx.gfo"

mkdir $TRAVIS_BUILD_DIR/pycutest_cache
export PYCUTEST_CACHE="$TRAVIS_BUILD_DIR/pycutest_cache"
export PYTHONPATH="${PYCUTEST_CACHE}:${PYTHONPATH}"

python3 setup.py install
python3 setup.py test



```

**Comment by jfowkes** [comment]
Hello, thank you for reporting. Apologies for the extremely delayed response, somehow I missed this.

This looks like a Fortran issue to me (see Issue #2): the "Failed to open data file" exception is thrown on line 115 of c_interface.py and indicates that the FORTRAN_open call on line 113 is failing for some reason. This could be due to incompatible Fortran compilers being used for CUTEst and PyCUTEst. 

Are you using Anaconda by any chance? Anaconda is known to use a different gfortran from the system default.
