### ISSUE TITLE
GCC error on ARM-based architecture

### ISSUE THREAD

**Issue by ragonneau** [jfowkes/pycutest#17]
# Bug description

After installing PyCUTEst as detailed in the [documentation](https://jfowkes.github.io/pycutest/_build/html/install.html#installing-cutest-on-linux), I cannot compile CUTEst problems via PyCUTEst. The tests of the Fortran source files (both `sifdecode` and `cutest`) succeed, but not the `import_problem` function.

I ran the following code:

```python
# Example: building problem
import pycutest

# Find unconstrained, variable-dimension problems
probs = pycutest.find_problems(constraints='U', userN=True)
print(sorted(probs)[:5])

# Properties of problem ROSENBR
print(pycuttest.problem_properties('ROSENBR'))

# Print parameters for problem ARGLALE
pycutest.print_available_sif_params('ARGLALE')

# Build this problem with N=100, M=200
problem = pycutest.import_problem('ARGLALE', sifParams={'N':100, 'M':200})
print(problem)
```

I got the following result:

```
['ARGLINA', 'ARGLINB', 'ARGLINC', 'ARGTRIGLS', 'ARWHEAD']
{'objective': 'S', 'constraints': 'U', 'regular': True, 'degree': 2, 'origin': 'A', 'internal': False, 'n': 2, 'm': 0}
Parameters available for problem ARGLALE:
N = 10 (int) 
N = 50 (int) 
N = 100 (int) 
N = 200 (int) [default]
M = 20 (int, .ge. N) 
M = 100 (int, .ge. N) 
M = 200 (int, .ge. N) 
M = 400 (int, .ge. N) [default]
End of parameters for problem ARGLALE
gcc: error: .2-a+fp16+rcpc+dotprod+crypto: No such file or directory
gcc: error: .2-a+fp16+rcpc+dotprod+crypto: No such file or directory
gcc: error: unrecognized command line option ‘-n1’; did you mean ‘-n’?
gcc: error: unrecognized command line option ‘-n1’; did you mean ‘-n’?
error: command '/usr/bin/gcc' failed with exit code 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tmr/anaconda3/envs/py39/lib/python3.9/site-packages/pycutest/build_interface.py", line 341, in import_problem
    compile_and_install_interface(problemName, destination, sifParams, sifOptions, efirst, lfirst, nvfirst, quiet)
  File "/home/tmr/anaconda3/envs/py39/lib/python3.9/site-packages/pycutest/build_interface.py", line 300, in compile_and_install_interface
    raise RuntimeError("Failed to build the Python interface module")
RuntimeError: Failed to build the Python interface module
```

To install CUTEst, I choose the options advocated in the [documentation](https://jfowkes.github.io/pycutest/_build/html/install.html#installing-cutest-on-linux).

# System settings

I am running PyCUTEst on the following ARM-based infrastructure.
- Python: 3.9.7 (default, Sep 16 2021, 16:31:42)  [GCC 10.2.0]
- Platform: Linux-4.15.0-166-generic-aarch64-with-glibc2.27

Details on the architecture:

```
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0,1
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
```

Version of GCC used:

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
```

Version of GFortran used:

```
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
```

**Comment by jfowkes** [comment]
Hello, thank you for your bug report. This is an Anaconda issue, being a compile-for-you python distribution, Anaconda's support for compiling python extensions is flaky / non-existent. As you are on a very recent architecture (64bit ARM) it does not at all surprise me that Anaconda is incapable of compiling the extensions that pycutest requires.

Please try using pycutest with your system python3 (by all means create a virtual environment for it). As you can see from your backtrace you are currently using an Anaconda environment which is where the issue lies.

**Comment by ragonneau** [comment]
Ok, I see, thank you very much for your quick reply!

Tom.
