### ISSUE TITLE
module 'pycutest_cache_holder.X' has no attribute 'setup'

### ISSUE THREAD

**Issue by jfowkes** [jfowkes/pycutest#51]
Regrettably PyCUTEst v1.5.0 breaks existing cached problems (we had to fix a memory leak).

When upgrading to PyCUTEst v1.5.0, please clear out your cache by deleting the $PYCUTEST_CACHE/pycutest_cache_holder directory:
```sh
rm -r $PYCUTEST_CACHE/pycutest_cache_holder/
```

Failure to do so will result in errors of the form:
```python
>>> pycutest.import_problem('ROSENBR')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jari/Code/pycutest/pycutest/build_interface.py", line 345, in import_problem
    return CUTEstProblem(importlib.import_module('%s.%s' % (CACHE_SUBFOLDER, problemDir)),
  File "/home/jari/Code/pycutest/pycutest/problem_class.py", line 52, in __new__
    module.info = module.setup() # setup CUTEst problem
AttributeError: module 'pycutest_cache_holder.ROSENBR' has no attribute 'setup'
```

**Comment by jfowkes** [comment]
Closing as outdated due to new major release.
