### ISSUE TITLE
Support for ARM-based Mac

### ISSUE THREAD

**Issue by tluedders** [jfowkes/pycutest#58]
Does this interface support ARM-based computers? I didn't read anything like that in the README, so hopefully I'm not missing something obvious. CUTEst itself seems to be working properly at first glance, although I couldn't do much testing.

I get the following output, when I try to run the example for building problems available at https://jfowkes.github.io/pycutest/_build/html/building.html#building-problems:

Parameters available for problem ARGLALE:
N = 10 (int) 
N = 50 (int) 
N = 100 (int) 
N = 200 (int) [default]
M = 20 (int, .ge. N) 
M = 100 (int, .ge. N) 
M = 200 (int, .ge. N) 
M = 400 (int, .ge. N) [default]
End of parameters for problem ARGLALE
ld: warning: ignoring file RANGE.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /opt/homebrew/opt/cutest/libexec/objects/mac64.osx.gfo/double/libcutest.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file GROUP.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file EXTER.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file ELFUN.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
Traceback (most recent call last):
  File "/Users/uni/Desktop/cutest/building_problems.py", line 8, in <module>
    problem = pycutest.import_problem('ARGLALE', sifParams={'N':100, 'M':200})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cutest/lib/python3.11/site-packages/pycutest/build_interface.py", line 354, in import_problem
    raise error
  File "/opt/anaconda3/envs/cutest/lib/python3.11/site-packages/pycutest/build_interface.py", line 345, in import_problem
    return CUTEstProblem(importlib.import_module('%s.%s' % (CACHE_SUBFOLDER, problemDir)),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cutest/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/uni/pycutest_cache/pycutest_cache_holder/ARGLALE_M200_N100/__init__.py", line 38, in <module>
    from ._pycutestitf import *
ImportError: dlopen(/Users/uni/pycutest_cache/pycutest_cache_holder/ARGLALE_M200_N100/_pycutestitf.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_cutest_cdh_'

Any feedback or tips to guide me in the right direction would be greatly appreciated.

**Comment by jfowkes** [comment]
Good question, yes it does but not on Anaconda as their support for compilation on ARM-base Macs is still very sketchy. See the related issue #17 

Our recommendation is to use homebrew python3 which should work.

**Comment by tluedders** [comment]
Awesome, that worked. Thanks for the quick help.
