### ISSUE TITLE
Problem compilation issue when pycutest.importing_problem(string) is called.

### ISSUE THREAD

**Issue by gillhofer** [jfowkes/pycutest#7]
When trying to import a problem 
> probname = "ROSENBR"
> ct = pycutest.import_problem(probname, quiet=False)

the following exception gets thrown. It looks like something is wrong with the resulting `.so` module file. The module file exists after the exception was thrown.

```
Problem name: ROSENBR

 Double precision version will be formed

 The objective function uses 1 linear group
 The objective function uses 1 nonlinear group
 
 There are 2 free variables
 
 
 File successfully decoded
gfortran -fPIC -c GROUP.f 
gfortran -fPIC -c EXTER.f 
gfortran -fPIC -c RANGE.f 
gfortran -fPIC -c ELFUN.f 
pydev debugger: process 36500 is connecting

pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
running build
running build_ext
building '_pycutestitf' extension
creating build
creating build/temp.linux-x86_64-3.7
gcc-9.1.0 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DLINUX -I/PATH/python-374/lib/python3.7/site-packages/numpy/core/include/numpy -I/system/PATH/cutest/cutest/include/ -I/PATH/python-374/include/python3.7m -c cutestitf.c -o build/temp.linux-x86_64-3.7/cutestitf.o
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
creating build/lib.linux-x86_64-3.7
gcc-9.1.0 -pthread -shared build/temp.linux-x86_64-3.7/cutestitf.o GROUP.o RANGE.o EXTER.o ELFUN.o /PATH/cutest/cutest/objects/pc64.lnx.gfo/double/libcutest.a -lgfortran -o build/lib.linux-x86_64-3.7/_pycutestitf.cpython-37m-x86_64-linux-gnu.so
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: process 36623 is connecting

pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /usr/lib/python3.7/site-packages/sympy/matrices/matrices.py (will have no effect)
running install
running build
running build_ext
running install_lib
copying build/lib.linux-x86_64-3.7/_pycutestitf.cpython-37m-x86_64-linux-gnu.so -> .
running install_egg_info
Writing ./PyCUTEst_automatic_test_function_interface_builder-1.0-py3.7.egg-info
Traceback (most recent call last):
  File "/system/PATH/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/system/PATH/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/system/PATH/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/system/PATH/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/system/PATH2/cutest_test.py", line 14, in <module>
    ct = pycutest.import_problem(probname, quiet=False)
  File "/system/PATHS/python-374/lib/python3.7/site-packages/pycutest/build_interface.py", line 336, in import_problem
    return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
  File "/PATH/pycutest_cache_folder/pycutest_cache_holder/ROSENBR/__init__.py", line 63, in <module>
    (n, m)=_pycutestitf._dims()
Exception: Failed to open data file
```

Somethings is odd here. Can you help me?

**Comment by jfowkes** [comment]
Looks like you might be mixing gfortran versions, did you compile CUTEst with the same version as given by `gfortran --version`?

**Comment by gillhofer** [comment]
That was indeed the problem. I needed to recompile `cutest` with a the compiler python was built. 

Now most of the attributes and methods of a `imported_problem` seem to work. However, there are a few which do not. e.g. `ct.getinfo()` is failing.

```
Traceback (most recent call last):
  File "/PATH/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
AttributeError: 'CUTEstProblem' object has no attribute 'getinfo'
```

The important parts like function evaluations seems to work, though.

**Comment by jfowkes** [comment]
Glad that fixed it, yes at the moment we only support gfortran and assume that `gfortran` points to the system default (which works for the vast majority of systems).

Regarding the `getinfo()` function, there isn't one: like the CUTEst fortran interface the relevant info is accessed directly from the problem class (e.g. `ct.n` gives the number of variables). See here for details: https://jfowkes.github.io/pycutest/_build/html/interface.html
