### ISSUE TITLE
Error finding CUTEst installation (new meson build)

### ISSUE THREAD

**Issue by AndrewLister-STFC** [jfowkes/pycutest#89]
**Describe the bug**
I get the following error on import:

```
root@31fb1c5ea579:/home/fitbenchmarking# python
Python 3.12.7 (main, Oct  8 2024, 00:20:25) [Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycutest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.12/site-packages/pycutest/__init__.py", line 7, in <module>
    from .build_interface import import_problem, clear_cache, all_cached_problems
  File "/opt/venv/lib/python3.12/site-packages/pycutest/build_interface.py", line 13, in <module>
    from .install_scripts import get_setup_script
  File "/opt/venv/lib/python3.12/site-packages/pycutest/install_scripts.py", line 95, in <module>
    """ % get_cutest_path()  # will probably get the homebrew location, but may revert to environment variables
          ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pycutest/system_paths.py", line 49, in get_cutest_path
    raise RuntimeError('Could not find CUTEST installation - have CUTEST and MYARCH environment variables been set correctly?')
RuntimeError: Could not find CUTEST installation - have CUTEST and MYARCH environment variables been set correctly?
```

I have installed CUTEst using the meson build system, so the path is not at the expected location:
```
$CUTEST/objects/$MYARCH/double/libcutest.a
```
and is instead installed and on the standard path
```
ls /usr/local/lib/libcutest_*
/usr/local/lib/libcutest_double.a  /usr/local/lib/libcutest_single.a
```

**To Reproduce**
I built CUTEst as part of a container [here](https://github.com/fitbenchmarking/fitbenchmarking/blob/ace9a272d0c636701892d2850d58c4132cebd01c/Container/Containerfile#L76).
(I plan to update SIFDecode to the meson build too).

**Information about your installation:**
 - Operating System: `ubuntu:24.04`
 - Python Version / Distribution: `uv python install 3.12`
 - PyCUTEst Version: `1.7.1`

**Comment by jfowkes** [comment]
@lindonroberts I guess we should now also check the standard `/usr/local/lib/` path? This is so that we can also support the newly released CUTEst meson installer that installs to `/usr/local/lib/` by default. The old makefile based CUTEst installer still uses the paths that we currently have so we should probably retain it for now.

**Comment by lindonroberts** [comment]
@jfowkes that makes sense to me. So the new meson installer just puts everything in a standard location and doesn't set the environment variables? Is it the same default path for Mac and Linux?

**Comment by jfowkes** [comment]
@lindonroberts good question, the meson docs are rather vague on the specifics:

> There is usually no need to specify install paths or the like. Meson will automatically install to the standards-conforming location.

I'll do some testing and see what the default Mac and Linux install locations are.

**Comment by AndrewLister-STFC** [comment]
You can add a prefix when you set up the meson build to give it a custom install directory. It might be enough to check for existence on the PATH env var?

Would something like this do the job?
```
import pathlib
import os
cutest_double_path = None
for p in os.environ["PATH"].split(":"):
    candidate = pathlib.Path(p)/'libcutest_double.so'
    if candidate.exists():
        cutest_path = candidate
        break
```

**Comment by jfowkes** [comment]
@AndrewLister-STFC no because `/usr/local/lib/` is not on `PATH` (path is for binaries not libraries). It is sometimes on `LD_LIBRARY_PATH` on Linux but this is not guaranteed, especially on Mac.

**Comment by jfowkes** [comment]
@lindonroberts after some testing here are the default meson install directories (for SIFDecode and CUTEst):

Linux
```
/usr/local/lib/
/usr/local/bin/
```

macOS (Silicon)
```
/opt/homebrew/lib/
/opt/homebrew/bin/
```

It looks like we already have the macOS paths so we just need to add the local Linux paths.
